version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdasd
      POSTGRES_DB: pm-crm

  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdasd
      POSTGRES_DB: pm-crm

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"