version: '3.8'
services:
  dev-db:
    image: postgres:13
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DOCKER_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"

  test-db:
    image: postgres:13
    ports:
      - "${TEST_DB_PORT}:${DOCKER_PORT}"
    environment:
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PASSWORD}"
      POSTGRES_DB: "${TEST_DB_NAME}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"