version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "${DEV_DB_PORT}:${DOCKER_PORT}"
    environment:
      POSTGRES_USER: "${DEV_DB_USER}"
      POSTGRES_PASSWORD: "${DEV_DB_PASSWORD}"
      POSTGRES_DB: "${DEV_DB_NAME}"

  prod-db:
    image: postgres:13
    ports:
      - "${PROD_DB_PORT}:${DOCKER_PORT}"
    environment:
      POSTGRES_USER: "${PROD_DB_USER}"
      POSTGRES_PASSWORD: "${PROD_DB_PASSWORD}"
      POSTGRES_DB: "${PROD_DB_NAME}"

  test-db:
    image: postgres:13
    ports:
      - "${TEST_DB_PORT}:${DOCKER_PORT}"
    environment:
      POSTGRES_USER: "${TEST_DB_USER}"
      POSTGRES_PASSWORD: "${TEST_DB_PASSWORD}"
      POSTGRES_DB: "${TEST_DB_NAME}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"